using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OOPConsoleProject.Scenes
{
    class End2 : BaseScene
    {
        private ConsoleKey input;
        public override void Render()
        {
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Clear();
            Console.WriteLine("                                                 /____________________\\                                                 ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine(" /\\                                                                                                                  /\\ ");
            Console.WriteLine("/  \\                                                                                                                /  \\"); 
            Console.WriteLine("    \\                                                                                                              /    ");

            Thread.Sleep(200);
            Console.Clear();

            Console.WriteLine("                                                  /                  \\                                                 ");
            Console.WriteLine("                                                 /____________________\\                                                ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("    /\\                                                                                                            /\\  ");
            Console.WriteLine("   /  \\                                                                                                          /  \\ ");
            Console.WriteLine("  /    \\                                                                                                        /    \\");
            Console.WriteLine(" /      \\                                                                                                      /      \\"); 
            Console.WriteLine("/        \\                                                                                                    /        \\");

            Thread.Sleep(200);
            Console.Clear();

            Console.WriteLine("                                                    /              \\                                                   ");
            Console.WriteLine("                                                   /                \\                                                  ");
            Console.WriteLine("                                                  /                  \\                                                 ");
            Console.WriteLine("                                                 /____________________\\                                                ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("          /\\                                                                                                /\\        ");
            Console.WriteLine("         /  \\                                                                                              /  \\       ");
            Console.WriteLine("        /    \\                                                                                            /    \\      ");
            Console.WriteLine("       /      \\                                                                                          /      \\     ");
            Console.WriteLine("      /        \\                                                                                        /        \\    ");
            Console.WriteLine("     /          \\                                                                                      /          \\   ");
            Console.WriteLine("    /            \\                                                                                    /            \\  ");
            Console.WriteLine("   /              \\                                                                                  /              \\ ");

            Thread.Sleep(200);
            Console.Clear();
            
            Console.WriteLine("                                                       /        \\                                                      ");
            Console.WriteLine("                                                      /          \\                                                     ");
            Console.WriteLine("                                                     /            \\                                                    ");
            Console.WriteLine("                                                    /              \\                                                   ");
            Console.WriteLine("                                                   /                \\                                                  ");
            Console.WriteLine("                                                  /                  \\                                                 ");
            Console.WriteLine("                                                 /____________________\\                                                ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                       /\\                                                                      /\\                     ");
            Console.WriteLine("                      /  \\                                                                    /  \\                    ");
            Console.WriteLine("                     /    \\                                                                  /    \\                   ");
            Console.WriteLine("                    /      \\                                                                /      \\                  ");
            Console.WriteLine("                   /        \\                                                              /        \\                 ");
            Console.WriteLine("                  /          \\                                                            /          \\                ");
            Console.WriteLine("                 /            \\                                                          /            \\               ");
            Console.WriteLine("                /              \\                                                        /              \\              ");
            Console.WriteLine("               /                \\                                                      /                \\             ");
            Console.WriteLine("              /                  \\                                                    /                  \\            ");
            Console.WriteLine("             /____________________\\                                                  /____________________\\           ");
           
            Thread.Sleep(200);
            Console.Clear();

            Console.WriteLine("                                                         /    \\                                                         ");
            Console.WriteLine("                                                        /      \\                                                        ");
            Console.WriteLine("                                                       /        \\                                                       ");
            Console.WriteLine("                                                      /          \\                                                      ");
            Console.WriteLine("                                                     /            \\                                                     ");
            Console.WriteLine("                                                    /              \\                                                    ");
            Console.WriteLine("                                                   /                \\                                                   ");
            Console.WriteLine("                                                  /                  \\                                                  ");
            Console.WriteLine("                                                 /____________________\\                                                 ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                               /\\                                                      /\\                             ");
            Console.WriteLine("                              /  \\                                                    /  \\                            ");
            Console.WriteLine("                             /    \\                                                  /    \\                           ");
            Console.WriteLine("                            /      \\                                                /      \\                          ");
            Console.WriteLine("                           /        \\                                              /        \\                         ");
            Console.WriteLine("                          /          \\                                            /          \\                        ");
            Console.WriteLine("                         /            \\                                          /            \\                       ");
            Console.WriteLine("                        /              \\                                        /              \\                      ");
            Console.WriteLine("                       /                \\                                      /                \\                     ");
            Console.WriteLine("                      /                  \\                                    /                  \\                    ");
            Console.WriteLine("                     /____________________\\                                  /____________________\\                   ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");

            Thread.Sleep(200);
            Console.Clear();

            Console.WriteLine("                                                           /\\                                                          ");
            Console.WriteLine("                                                          /  \\                                                         ");
            Console.WriteLine("                                                         /    \\                                                        ");
            Console.WriteLine("                                                        /      \\                                                       ");
            Console.WriteLine("                                                       /        \\                                                      ");
            Console.WriteLine("                                                      /          \\                                                     ");
            Console.WriteLine("                                                     /            \\                                                    ");
            Console.WriteLine("                                                    /              \\                                                   ");
            Console.WriteLine("                                                   /                \\                                                  ");
            Console.WriteLine("                                                  /                  \\                                                 ");
            Console.WriteLine("                                                 /____________________\\                                                ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                     /\\                                          /\\                                   ");
            Console.WriteLine("                                    /  \\                                        /  \\                                  ");
            Console.WriteLine("                                   /    \\                                      /    \\                                 ");
            Console.WriteLine("                                  /      \\                                    /      \\                                ");
            Console.WriteLine("                                 /        \\                                  /        \\                               ");
            Console.WriteLine("                                /          \\                                /          \\                              ");
            Console.WriteLine("                               /            \\                              /            \\                             ");
            Console.WriteLine("                              /              \\                            /              \\                            ");
            Console.WriteLine("                             /                \\                          /                \\                           ");
            Console.WriteLine("                            /                  \\                        /                  \\                          ");
            Console.WriteLine("                           /____________________\\                      /____________________\\                         ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");

            Thread.Sleep(200);
            Console.Clear();

            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                           /\\                                                          ");
            Console.WriteLine("                                                          /  \\                                                         ");
            Console.WriteLine("                                                         /    \\                                                        ");
            Console.WriteLine("                                                        /      \\                                                       ");
            Console.WriteLine("                                                       /        \\                                                      ");
            Console.WriteLine("                                                      /          \\                                                     ");
            Console.WriteLine("                                                     /            \\                                                    ");
            Console.WriteLine("                                                    /              \\                                                   ");
            Console.WriteLine("                                                   /                \\                                                  ");
            Console.WriteLine("                                                  /                  \\                                                 ");
            Console.WriteLine("                                                 /____________________\\                                                ");
            Console.WriteLine("                                               /\\                      /\\                                             ");
            Console.WriteLine("                                              /  \\                    /  \\                                            ");
            Console.WriteLine("                                             /    \\                  /    \\                                           ");
            Console.WriteLine("                                            /      \\                /      \\                                          ");
            Console.WriteLine("                                           /        \\              /        \\                                         ");
            Console.WriteLine("                                          /          \\            /          \\                                        ");
            Console.WriteLine("                                         /            \\          /            \\                                       ");
            Console.WriteLine("                                        /              \\        /              \\                                      ");
            Console.WriteLine("                                       /                \\      /                \\                                     ");
            Console.WriteLine("                                      /                  \\    /                  \\                                    ");
            Console.WriteLine("                                     /____________________\\  /____________________\\                                   ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");

            Thread.Sleep(200);
            Console.Clear();

            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                           /\\                                                          ");
            Console.WriteLine("                                                          /  \\                                                         ");
            Console.WriteLine("                                                         /    \\                                                        ");
            Console.WriteLine("                                                        /      \\                                                       ");
            Console.WriteLine("                                                       /        \\                                                      ");
            Console.WriteLine("                                                      /          \\                                                     ");
            Console.WriteLine("                                                     /            \\                                                    ");
            Console.WriteLine("                                                    /              \\                                                   ");
            Console.WriteLine("                                                   /                \\                                                  ");
            Console.WriteLine("                                                  /                  \\                                                 ");
            Console.WriteLine("                                                 /____________________\\                                                ");
            Console.WriteLine("                                               /\\                      /\\                                             ");
            Console.WriteLine("                                              /  \\                    /  \\                                            ");
            Console.WriteLine("                                             /    \\                  /    \\                                           ");
            Console.WriteLine("                                            /      \\                /      \\                                          ");
            Console.WriteLine("                                           /        \\              /        \\                                         ");
            Console.WriteLine("                                          /          \\            /          \\                                        ");
            Console.WriteLine("                                         /            \\          /            \\                                       ");
            Console.WriteLine("                                        /              \\        /              \\                                      ");
            Console.WriteLine("                                       /                \\      /                \\                                     ");
            Console.WriteLine("                                      /                  \\    /                  \\                                    ");
            Console.WriteLine("                                     /____________________\\  /____________________\\                                   ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");

            Thread.Sleep(200);
            Console.Clear();

            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                           /\\                                                          ");
            Console.WriteLine("                                                          /  \\                                                         ");
            Console.WriteLine("                                                         /    \\                                                        ");
            Console.WriteLine("                                                        /      \\                                                       ");
            Console.WriteLine("                                                       /        \\                                                      ");
            Console.WriteLine("                                                      /          \\                                                     ");
            Console.WriteLine("                                                     /            \\                                                    ");
            Console.WriteLine("                                                  _   __                             _  _      ___                      ");
            Console.WriteLine("                                                 | | / /                            (_)| |    / _ \\                     ");
            Console.WriteLine("           ___  ___   ___   __ _  _ __    ___    | |/ /  _   _  _   _  _ __    __ _  _ | |   / /_\\ \\  ___   __ _        ");
            Console.WriteLine("          / _ \\/ __| / __| / _` || '_ \\  / _ \\   |    \\ | | | || | | || '_ \\  / _` || || |   |  _  | / __| / _` |       ");
            Console.WriteLine("         |  __/\\__ \\| (__ | (_| || |_) ||  __/   | |\\  \\| |_| || |_| || | | || (_| || || |   | | | || (__ | (_| |       ");
            Console.WriteLine("          \\___||___/ \\___| \\__,_|| .__/  \\___|   \\_| \\_/ \\__, | \\__,_||_| |_| \\__, ||_||_|   \\_| |_/ \\___| \\__,_|       ");
            Console.WriteLine("                                 | |                      __/ |                __/ |                                    ");
            Console.WriteLine("                                 |_|                     |___/                |___/                                     ");
            Console.WriteLine("                                           /        \\              /        \\                                         ");
            Console.WriteLine("                                          /          \\            /          \\                                        ");
            Console.WriteLine("                                         /            \\          /            \\                                       ");
            Console.WriteLine("                                        /              \\        /              \\                                      ");
            Console.WriteLine("                                       /                \\      /                \\                                     ");
            Console.WriteLine("                                      /                  \\    /                  \\                                    ");
            Console.WriteLine("                                     /____________________\\  /____________________\\                                   ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");

            Thread.Sleep(2000);
            Console.Clear();

            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                           /\\                                                          ");
            Console.WriteLine("                                                          /  \\                                                         ");
            Console.WriteLine("                                                         /    \\                                                        ");
            Console.WriteLine("                                                        /      \\                                                       ");
            Console.WriteLine("                                                       /        \\                                                      ");
            Console.WriteLine("                                                      /          \\                                                     ");
            Console.WriteLine("                                                     /            \\                                                    ");
            Console.WriteLine("                                                  _   __                             _  _      ___                      ");
            Console.WriteLine("                                                 | | / /                            (_)| |    / _ \\                     ");
            Console.WriteLine("           ___  ___   ___   __ _  _ __    ___    | |/ /  _   _  _   _  _ __    __ _  _ | |   / /_\\ \\  ___   __ _        ");
            Console.WriteLine("          / _ \\/ __| / __| / _` || '_ \\  / _ \\   |    \\ | | | || | | || '_ \\  / _` || || |   |  _  | / __| / _` |       ");
            Console.WriteLine("         |  __/\\__ \\| (__ | (_| || |_) ||  __/   | |\\  \\| |_| || |_| || | | || (_| || || |   | | | || (__ | (_| |       ");
            Console.WriteLine("          \\___||___/ \\___| \\__,_|| .__/  \\___|   \\_| \\_/ \\__, | \\__,_||_| |_| \\__, ||_||_|   \\_| |_/ \\___| \\__,_|       ");
            Console.WriteLine("                                 | |                      __/ |                __/ |                                    ");
            Console.WriteLine("                                 |_|                     |___/                |___/                                     ");
            Console.WriteLine("                                           /        \\              /        \\                                         ");
            Console.WriteLine("                                          /          \\            /          \\                                        ");
            Console.WriteLine("                                         /            \\          /            \\                                       ");
            Console.WriteLine("                                        /              \\        /              \\                                      ");
            Console.WriteLine("                                       /                \\      /                \\                                     ");
            Console.WriteLine("                                      /                  \\    /                  \\                                    ");
            Console.WriteLine("                                     /____________________\\  /____________________\\                                   ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");

            Thread.Sleep(200);
            Console.Clear();

            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                           /\\                                                          ");
            Console.WriteLine("                                                          /  \\                                                         ");
            Console.WriteLine("                                                         /    \\                                                        ");
            Console.WriteLine("                                                        /      \\                                                       ");
            Console.WriteLine("                                                       /        \\                                                      ");
            Console.WriteLine("                                                      /          \\                                                     ");
            Console.WriteLine("                                                     /            \\                                                    ");
            Console.WriteLine("                                                    /              \\                                                   ");
            Console.WriteLine("                                                   /                \\                                                  ");
            Console.WriteLine("                                                  /                  \\                                                 ");
            Console.WriteLine("                                                 /____________________\\                                                ");
            Console.WriteLine("                                               /\\                      /\\                                             ");
            Console.WriteLine("                                              /  \\                    /  \\                                            ");
            Console.WriteLine("                                             /    \\                  /    \\                                           ");
            Console.WriteLine("                                            /      \\                /      \\                                          ");
            Console.WriteLine("                                           /        \\              /        \\                                         ");
            Console.WriteLine("                                          /          \\            /          \\                                        ");
            Console.WriteLine("                                         /            \\          /            \\                                       ");
            Console.WriteLine("                                        /              \\        /              \\                                      ");
            Console.WriteLine("                                       /                \\      /                \\                                     ");
            Console.WriteLine("                                      /                  \\    /                  \\                                    ");
            Console.WriteLine("                                     /____________________\\  /____________________\\                                   ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");

            Thread.Sleep(200);
            Console.Clear();

            Console.WriteLine("                                                           /\\                                                          ");
            Console.WriteLine("                                                          /  \\                                                         ");
            Console.WriteLine("                                                         /    \\                                                        ");
            Console.WriteLine("                                                        /      \\                                                       ");
            Console.WriteLine("                                                       /        \\                                                      ");
            Console.WriteLine("                                                      /          \\                                                     ");
            Console.WriteLine("                                                     /            \\                                                    ");
            Console.WriteLine("                                                    /              \\                                                   ");
            Console.WriteLine("                                                   /                \\                                                  ");
            Console.WriteLine("                                                  /                  \\                                                 ");
            Console.WriteLine("                                                 /____________________\\                                                ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                     /\\                                          /\\                                   ");
            Console.WriteLine("                                    /  \\                                        /  \\                                  ");
            Console.WriteLine("                                   /    \\                                      /    \\                                 ");
            Console.WriteLine("                                  /      \\                                    /      \\                                ");
            Console.WriteLine("                                 /        \\                                  /        \\                               ");
            Console.WriteLine("                                /          \\                                /          \\                              ");
            Console.WriteLine("                               /            \\                              /            \\                             ");
            Console.WriteLine("                              /              \\                            /              \\                            ");
            Console.WriteLine("                             /                \\                          /                \\                           ");
            Console.WriteLine("                            /                  \\                        /                  \\                          ");
            Console.WriteLine("                           /____________________\\                      /____________________\\                         ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");

            Thread.Sleep(200);
            Console.Clear();

            Console.WriteLine("                                                         /    \\                                                         ");
            Console.WriteLine("                                                        /      \\                                                        ");
            Console.WriteLine("                                                       /        \\                                                       ");
            Console.WriteLine("                                                      /          \\                                                      ");
            Console.WriteLine("                                                     /            \\                                                     ");
            Console.WriteLine("                                                    /              \\                                                    ");
            Console.WriteLine("                                                   /                \\                                                   ");
            Console.WriteLine("                                                  /                  \\                                                  ");
            Console.WriteLine("                                                 /____________________\\                                                 ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                               /\\                                                      /\\                             ");
            Console.WriteLine("                              /  \\                                                    /  \\                            ");
            Console.WriteLine("                             /    \\                                                  /    \\                           ");
            Console.WriteLine("                            /      \\                                                /      \\                          ");
            Console.WriteLine("                           /        \\                                              /        \\                         ");
            Console.WriteLine("                          /          \\                                            /          \\                        ");
            Console.WriteLine("                         /            \\                                          /            \\                       ");
            Console.WriteLine("                        /              \\                                        /              \\                      ");
            Console.WriteLine("                       /                \\                                      /                \\                     ");
            Console.WriteLine("                      /                  \\                                    /                  \\                    ");
            Console.WriteLine("                     /____________________\\                                  /____________________\\                   ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");

            Thread.Sleep(200);
            Console.Clear();

            Console.WriteLine("                                                       /        \\                                                      ");
            Console.WriteLine("                                                      /          \\                                                     ");
            Console.WriteLine("                                                     /            \\                                                    ");
            Console.WriteLine("                                                    /              \\                                                   ");
            Console.WriteLine("                                                   /                \\                                                  ");
            Console.WriteLine("                                                  /                  \\                                                 ");
            Console.WriteLine("                                                 /____________________\\                                                ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                       /\\                                                                      /\\                     ");
            Console.WriteLine("                      /  \\                                                                    /  \\                    ");
            Console.WriteLine("                     /    \\                                                                  /    \\                   ");
            Console.WriteLine("                    /      \\                                                                /      \\                  ");
            Console.WriteLine("                   /        \\                                                              /        \\                 ");
            Console.WriteLine("                  /          \\                                                            /          \\                ");
            Console.WriteLine("                 /            \\                                                          /            \\               ");
            Console.WriteLine("                /              \\                                                        /              \\              ");
            Console.WriteLine("               /                \\                                                      /                \\             ");
            Console.WriteLine("              /                  \\                                                    /                  \\            ");
            Console.WriteLine("             /____________________\\                                                  /____________________\\           ");

            Thread.Sleep(200);
            Console.Clear();

            Console.WriteLine("                                                    /              \\                                                   ");
            Console.WriteLine("                                                   /                \\                                                  ");
            Console.WriteLine("                                                  /                  \\                                                 ");
            Console.WriteLine("                                                 /____________________\\                                                ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("          /\\                                                                                                /\\        ");
            Console.WriteLine("         /  \\                                                                                              /  \\       ");
            Console.WriteLine("        /    \\                                                                                            /    \\      ");
            Console.WriteLine("       /      \\                                                                                          /      \\     ");
            Console.WriteLine("      /        \\                                                                                        /        \\    ");
            Console.WriteLine("     /          \\                                                                                      /          \\   ");
            Console.WriteLine("    /            \\                                                                                    /            \\  ");
            Console.WriteLine("   /              \\                                                                                  /              \\ ");

            Thread.Sleep(200);
            Console.Clear();

            Console.WriteLine("                                                  /                  \\                                                 ");
            Console.WriteLine("                                                 /____________________\\                                                ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("    /\\                                                                                                            /\\  ");
            Console.WriteLine("   /  \\                                                                                                          /  \\ ");
            Console.WriteLine("  /    \\                                                                                                        /    \\");
            Console.WriteLine(" /      \\                                                                                                      /      \\");
            Console.WriteLine("/        \\                                                                                                    /        \\");

            Thread.Sleep(200);
            Console.Clear();
            Console.WriteLine("                                                 /____________________\\                                                 ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine(" /\\                                                                                                                  /\\ ");
            Console.WriteLine("/  \\                                                                                                                /  \\");
            Console.WriteLine("    \\                                                                                                              /    ");

            Thread.Sleep(200);
            Console.Clear();
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                     _    _                _                      _                _                                    ");
            Console.WriteLine("                    | |  | |              | |                    | |              (_)                                   ");
            Console.WriteLine("                    | |_ | |__  __  __    | |_   ___       _ __  | |  __ _  _   _  _  _ __    __ _                      ");
            Console.WriteLine("                    | __|| '_ \\ \\ \\/ /    | __| / _ \\     | '_ \\ | | / _` || | | || || '_ \\  / _` |                     ");
            Console.WriteLine("                    | |_ | | | | >  <     | |_ | (_) |    | |_) || || (_| || |_| || || | | || (_| |                     ");
            Console.WriteLine("                     \\__||_| |_|/_/\\_\\     \\__| \\___/     | .__/ |_| \\__,_| \\__, ||_||_| |_| \\__, |                     ");
            Console.WriteLine("                                                          | |                __/ |            __/ |                     ");
            Console.WriteLine("                                                          |_|               |___/            |___/                      ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Thread.Sleep(1000);
            Console.WriteLine("                               제작자의 한 줄 소감을 들으려면 아무키나 눌러서 계속...                                   ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.WriteLine("                                                                                                                        ");
            Console.ResetColor();



        }

        public override void Input()
        {
            input = Console.ReadKey(true).Key;
        }

        public override void Update()
        {
            switch (input)
            {
                default:
                    Game.gameOver = true;
                    break;
            }
        }

        public override void Result()
        {
            //Game.ChangeScene("KyungilGameAcademymainhall"); //자동이동기능
        }
    }
}
